APP_VERSION_CODE=1600
APP_VERSION_NAME=1.6.0

org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableR8.fullMode=true
android.nonTransitiveRClass=false
android.nonFinalResIds=true
android.overridePathCheck=true
