/*
 * This file is generated by scripts/set-build-channel.mjs.
 * DO NOT EDIT MANUALLY.
 */

export const BUILD_STABLE_APP_URL = "https://astraof.com" as const;
export const BUILD_CANARY_APP_URL = "https://astraof.com" as const;
export const BUILD_TRUSTED_APP_URLS = ["https://astraof.com","https://asrtal.ru"] as const;
export const BUILD_DESKTOP_UPDATE_ORIGINS = ["https://astraof.com","https://asrtal.ru"] as const;
